### ISSUE TITLE
NPE in the console logs when installing the firs paid app

### ISSUE THREAD

**Issue by Enygma2002** [xwikisas/application-licensing#51] opened 2018-11-01 15:05 UTC
On XWiki 9.2, when first installing a paid app that brings in the licensor-api as dependency, I get the following NPE stacktrace in the logs:
```
2018-11-01 16:34:32,983 [http://localhost:9090/xwiki/bin/get/XWiki/Extensions] ERROR .a.DefaultAuthorizationManager - Failed to load rights for user [xwiki:XWiki.Admin] on [xwiki:AnnotationCode.Settings]. 
java.lang.RuntimeException: Failed to get [role = [interface com.xwiki.licensing.LicenseManager] hint = [default]]
        at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:103)
        at com.xwiki.licensing.internal.enforcer.DefaultEntityLicenseManager.getLicenseManager(DefaultEntityLicenseManager.java:79)
        at com.xwiki.licensing.internal.enforcer.DefaultEntityLicenseManager.getLicenses(DefaultEntityLicenseManager.java:103)
        at com.xwiki.licensing.internal.enforcer.DefaultEntityLicenseManager.get(DefaultEntityLicenseManager.java:91)
        at com.xwiki.licensing.internal.enforcer.LicensingSecurityEntryReader.read(LicensingSecurityEntryReader.java:160)
        at org.xwiki.security.authorization.cache.internal.DefaultSecurityCacheLoader.getRules(DefaultSecurityCacheLoader.java:447)
        at org.xwiki.security.authorization.cache.internal.DefaultSecurityCacheLoader.loadRequiredEntries(DefaultSecurityCacheLoader.java:190)
        at org.xwiki.security.authorization.cache.internal.DefaultSecurityCacheLoader.load(DefaultSecurityCacheLoader.java:148)
        at org.xwiki.security.authorization.DefaultAuthorizationManager.getAccess(DefaultAuthorizationManager.java:218)
        at org.xwiki.security.authorization.DefaultAuthorizationManager.evaluateSecurityAccess(DefaultAuthorizationManager.java:159)
        at org.xwiki.security.authorization.DefaultAuthorizationManager.hasSecurityAccess(DefaultAuthorizationManager.java:152)
        at org.xwiki.security.authorization.DefaultAuthorizationManager.hasAccess(DefaultAuthorizationManager.java:109)
        at org.xwiki.security.authorization.internal.DefaultContextualAuthorizationManager.hasAccess(DefaultContextualAuthorizationManager.java:136)
        at org.xwiki.security.authorization.internal.DefaultContextualAuthorizationManager.hasAccess(DefaultContextualAuthorizationManager.java:131)
        at com.xpn.xwiki.plugin.skinx.AbstractDocumentSkinExtensionPlugin.isAccessible(AbstractDocumentSkinExtensionPlugin.java:393)
        at com.xpn.xwiki.plugin.skinx.JsSkinExtensionPlugin.getLink(JsSkinExtensionPlugin.java:88)
        at com.xpn.xwiki.plugin.skinx.AbstractSkinExtensionPlugin.getImportString(AbstractSkinExtensionPlugin.java:253)
        at com.xpn.xwiki.plugin.skinx.AbstractSkinExtensionPlugin.endParsing(AbstractSkinExtensionPlugin.java:354)
        at com.xpn.xwiki.plugin.skinx.AbstractDocumentSkinExtensionPlugin.endParsing(AbstractDocumentSkinExtensionPlugin.java:284)
        at com.xpn.xwiki.plugin.skinx.JsSkinExtensionPlugin.endParsing(JsSkinExtensionPlugin.java:130)
        at com.xpn.xwiki.plugin.XWikiPluginManager.endParsing(XWikiPluginManager.java:275)
        at com.xpn.xwiki.web.Utils.parseTemplate(Utils.java:184)
        at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:463)
        at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:210)
        at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
        at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:112)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.xwiki.wysiwyg.server.filter.ConversionFilter.doFilter(ConversionFilter.java:127)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.xwiki.container.servlet.filters.internal.SetHTTPHeaderFilter.doFilter(SetHTTPHeaderFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.xwiki.resource.servlet.RoutingFilter.doFilter(RoutingFilter.java:134)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [com.xwiki.licensing.internal.DefaultLicenseManager] identified by [role = [interface com.xwiki.licensing.LicenseManager] hint = [default]]
        at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:394)
        at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:190)
        at org.xwiki.component.embed.GenericProvider.getInstance(GenericProvider.java:111)
        at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:100)
        ... 62 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.xwiki.licensing.internal.DefaultLicenseManager.initialize(DefaultLicenseManager.java:113)
        at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
        at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:322)
        at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:424)
        at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:392)
        ... 65 common frames omitted

```

**Comment by ilieandriuta** [comment] 2019-01-16 11:16
I also reproduced the issue on XWiki 10.8.3 after installing the first PRO app (Polls in this case).

**Comment by mflorea** [comment] 2019-02-02 13:57
The issue seems to be the fact that the components from ``application-licensing-licensor-api`` are loaded by the component manager before the extension they are part of is marked as installed. So when one of these components, ``DefaultLicenseManager``, tries to look up the installed ``application-licensing-licensor-api`` extension (in order to find its version), it fails.

**Closed** 2019-02-04 10:22 UTC
Labels: Priority: Major, Type: Bug
