### ISSUE TITLE
XWiki is locked down when a licensed application is installed on farm level

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-licensing#29] opened 2018-02-26 17:37 UTC
Environment: `xwiki-platform-distribution-flavor-jetty-hsqldb-10.1` ([downloaded here](http://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-distribution-flavor-jetty-hsqldb/10.1/))

Steps to reproduce:

1. Go to the administration and install an extension depending on `application-licensing` at farm level (I'm using the OnlyOffice connector) ;
1. The extension will not work without a proper trial license ; go to http://localhost:8080/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=Licenses to generate a new one ;
1. Notice that when clicking on "Get Trial" after filling in the form, you get an error ;
1. Refresh the page and notice that, even if we got an error message, a license has been installed ;
1. Restart XWiki ;
1. During the first access to a wiki page (when the browser shows "XWiki is initializing …"), notice that you get a lot of error in your console. FTR, [here is one](https://up1.xwikisas.com/#er1Z9Nb74ht_JMmRRIIM2w). One exception is thrown per wiki page ;
1. Once the initialization is finished, notice that you cannot access any wiki page.

**Comment by aubincleme** [comment] 2018-02-26 17:38
Note that I haven't worked out why this problem does not occur when the extension isn't "activated" (ie: has no license).

**Comment by mflorea** [comment] 2018-02-27 09:08
@aubincleme the licensing application is **always** installed on farm. You probably mean "XWiki is locked down when a licensed application is installed on farm level".

**Comment by mflorea** [comment] 2018-02-27 09:11
The relevant part of the stacktrace:

    Caused by: java.lang.NullPointerException: null
	    at com.xwiki.licensing.internal.enforcer.DefaultLicensingSecurityCacheRuleInvalidator.invalidate(DefaultLicensingSecurityCacheRuleInvalidator.java:97)
	    at com.xwiki.licensing.internal.DefaultLicenseManager.clearSecurityCacheForXarExtension(DefaultLicenseManager.java:393)
	    at com.xwiki.licensing.internal.DefaultLicenseManager.registerLicense(DefaultLicenseManager.java:238)
	    at com.xwiki.licensing.internal.DefaultLicenseManager.linkLicenseToInstalledExtensions(DefaultLicenseManager.java:182)
	    at com.xwiki.licensing.internal.DefaultLicenseManager.initialize(DefaultLicenseManager.java:132)
	    at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
	    at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:360)
	    at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:446)
	    at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:196)
	    ... 76 common frames omitted

**Comment by aubincleme** [comment] 2018-02-27 09:12
Indeed

**Comment by mflorea** [comment] 2018-02-27 09:21
Fixed by #28.

**Closed by mflorea** 2018-02-27 09:21 UTC
