### ISSUE TITLE
NPE Error when installing Pro Apps on XWiki 15.x

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-licensing#149] opened 2023-09-13 13:01 UTC
Environment: Windows 11 Pro, Chrome 117, using a local instance of XWiki 15.5.2 on PostgreSQL 15, Tomcat 9.0.80, Java 17 (Oracle) , Active Directory Application 1.16.3

STEPS TO REPRODUCE

1. Start an instance of XWiki 15.5.2
2. Install Active Directory Application (tested with 1.16.3)
3. Observe the XWiki console

EXPECTED RESULTS

No errors/ warnings are displayed.

ACTUAL RESULTS

Near the moment when the installation process is finished, the following NPE Error is encountered:

```
2023-09-13 15:40:03,712 [extension/wiki:xwiki job group daemon thread - org.xwiki.extension.job.internal.InstallJob@7bcc3a81([extension, action, com.xwiki.activedirectory:application-activedirectory-ui, wiki:xwiki])] ERROR .o.i.DefaultObservationManager - Failed to send event [org.xwiki.job.event.JobFinishedEvent@3692ce61] to listener [com.xpn.xwiki.XWiki@714162c1]
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "authClass" is null
        at com.xpn.xwiki.XWiki.onJobFinished(XWiki.java:7905)
        at com.xpn.xwiki.XWiki.onEvent(XWiki.java:7862)
        at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:338)
        at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:303)
        at org.xwiki.job.AbstractJob.jobFinished(AbstractJob.java:338)
        at org.xwiki.extension.job.internal.AbstractExtensionJob.jobFinished(AbstractExtensionJob.java:134)
        at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:251)
        at org.xwiki.job.AbstractJob.run(AbstractJob.java:223)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

The issue was reproduced also when installing AD on XWiki 15.3, but could not be reproduced on XWiki 14.10.16.

**Comment by ilieandriuta** [comment] 2023-09-14 11:05
The issue reproduced also when installing Diagram Pro 1.19 and Google Apps Integration Pro 2.6, but it seems it doesn't reproduce every time.
I also tested by installing contrib counterparts of some Pro apps (e.g. Diagram) and the issue didn't reproduce.

**Comment by ilieandriuta** [comment] 2023-09-14 11:41
It seems the NPE also reproduced when uninstalling the Pro Applications (reproduced when uninstalled File Manager Pro 2.6).

**Comment by oanalavinia** [comment] 2023-10-03 12:59
Closing it since it can be reproduced for non-pro apps as well, so it shouldn't be related to licensing

**Closed by oanalavinia** 2023-10-03 12:59 UTC
Labels: Type: Bug, Priority: Blocker
